import {
  IconBat,
  IconBook,
  IconBug,
  IconButterfly,
  IconCat,
  IconCoins,
  IconCrown,
  IconDeer,
  IconDiamond,
  IconDragon,
  IconFish,
  IconFlask,
  IconGhost,
  IconHorse,
  IconKey,
  IconLamp,
  IconMap,
  IconMouse,
  IconScript,
  IconShield,
  IconSkull,
  IconSpider,
  IconSword,
  IconTreasureChest,
  type Icon,
} from "@tabler/icons-react";
import type { TreasureId } from "@labyrinth/rules";

/** One Tabler icon per treasure. Typed over every TreasureId, so a missing icon is a compile error. */
export const TREASURE_ICONS: Record<TreasureId, Icon> = {
  crown: IconCrown,
  key: IconKey,
  gem: IconDiamond,
  coins: IconCoins,
  sword: IconSword,
  shield: IconShield,
  book: IconBook,
  map: IconMap,
  scroll: IconScript,
  potion: IconFlask,
  lamp: IconLamp,
  chest: IconTreasureChest,
  dragon: IconDragon,
  bat: IconBat,
  spider: IconSpider,
  butterfly: IconButterfly,
  ghost: IconGhost,
  cat: IconCat,
  fish: IconFish,
  horse: IconHorse,
  beetle: IconBug,
  mouse: IconMouse,
  skull: IconSkull,
  deer: IconDeer,
};
